# STUDY NOTES

## TUESDAY - 3

P12 - EXPERIMENTAL - kfan@laurentian.ca - CHECK - accent
P14 - CONTROL - bituaobaitua@laurentian.ca - CHECK - slight accent
P17 - EXPERIMENTAL - jomiadeleye14@gmail.com - CHECK - accent

## WEDNESDAY - 7 - All showed up + more

P27 - CONTROL - RAmon@laurentian.ca (11:00 AM) - CHECK - accent
P28 - EXPERIMENTAL - ejarvis@laurentan.ca (12:00 PM) - CHECK 
P29 - CONTROL - unisar@laurentian.ca (1:00 PM) - accent
P30 - CONTROL - cminn@laurentian.ca (2:00 PM) - substantial accent
P31 - EXPERIMENTAL - Brook Vrbanic brooke.vrbanic@gmail.com (2:40 ish)
P32 - EXPERIMENTAL - lji@laurentian.ca (this one comes after ywang54 timewise) (3:40 ish) - substantial accent
P33 - EXPERIMENTAL - ywang54@laurentian.ca (3:00ish) - substantial accent

## Thursday - 4

P35 - EXPERIMENTAL - ccui1@laurentian.ca (10am) - CHECK - This session went VERY long (45 mins) - substantial accent
EXPERIMENTAL - aisrail@laurentian.ca (1pm) - NO-SHOW
EXPERIMENTAL - ybarot@laurentian.ca (2pm) - NO-SHOW
P36 - CONTROL - kspriggs@laurentian.ca (also 2pm) - CHECK - FORGOT HIS TIMMIES
P37 - EXPERIMENTAL - bvachon@laurentian.ca (3pm) - CHECK - PSYCH student
P38 - CONTROL - pvyas@laurentian.ca (3:30)  - CHECK - accent

## Friday (4) - 18 so far

Need to figure out what happened; somehow, despite selecting CONTROL, it served up RESPONSIVE mode
P40 - CONTROL - bomoyele@laurentian.ca (10aml)- CHECK - accent - checked logs and looks lke it ran EXPERIMENTAL
P41 - CONTROL - gluoma@laurentian.ca (11am) - psych student - checked logs and looks like it ran EXPERIMENTAL 
P42 - EXPERIMENTAL - sxie2@laurentian.ca (12pm) - RAN AS CONTROL TO BALANCE but it still ran RESPONSIVE I THINK
P45 - EXPERIMENTAL -  Myan (1:20pm) - Think I figured out the prob
P46 - CONTROL - Lydia
P47 - CONTROL - Other
P48 - EXPERIMENTAL - Frankie
:::
Kyle Spriggs - 2pm Thursday

- multi-robot collaboration
P12,2025-11-10T18:00:35Z,2025-11-19T13:21:28Z,EXPERIMENTAL,unisar@laurentian.ca --WRONG
P14,2025-11-10T18:22:16Z,2025-11-19T14:07:37Z,CONTROL,cminn@laurentian.ca - 
P17,2025-11-10T18:58:13Z,2025-11-18T10:20:26Z,EXPERIMENTAL,kfan@laurentian.ca - 
P27,2025-11-10T23:08:30Z,2025-11-18T13:51:10Z,CONTROL,bituaobaitua@laurentian.ca  - 
P28,2025-11-11T08:47:14Z,2025-11-19T12:08:50Z,EXPERIMENTAL,ejarvis@laurentian.ca - 
P29,2025-11-11T09:36:13Z,2025-11-20T10:51:42Z,CONTROL,ccui1@laurentian.ca - WRONG
P30,2025-11-12T00:54:07Z,2025-11-21T10:26:19Z,CONTROL,bomoyele@laurentian.ca - 
P31,2025-11-12T17:44:40Z,2025-11-20T15:14:04Z,EXPERIMENTAL,bvachon1@laurentian.ca 
P32,2025-11-13T10:38:46Z,2025-11-19T15:46:38Z,EXPERIMENTAL,lji@laurentian.ca
P33,2025-11-13T16:18:18Z,2025-11-18T15:13:46Z,EXPERIMENTAL,jomiadeleye14@gmail.com 
P35,2025-11-17T09:56:28Z,2025-11-19T11:09:09Z,EXPERIMENTAL,RAmon@laurentian.ca - WRONG
P36,2025-11-18T20:26:34Z,2025-11-21T12:38:13Z,CONTROL,sxie2@laurentian.ca - WRONG
P37,2025-11-19T11:59:03Z,2025-11-21T11:31:19Z,EXPERIMENTAL,gluoma@laurentian.ca - WRONG
P38,2025-11-19T13:53:45Z,2025-11-19T14:33:49Z,CONTROL,brooke.vrbanic@gmail.com - WRONG
P40,2025-11-20T13:44:44Z,2025-11-20T15:51:39Z,EXPERIMENTAL,pvyas@laurentian.ca - WRONG
P41,2025-11-20T14:07:15Z,2025-11-20T14:45:19Z,EXPERIMENTAL,kspriggs@laurentian.ca - WRONG
P42,2025-11-21T13:06:57Z,2025-11-21T13:29:31Z,EXPERIMENTAL,gagnon.myan06@gmail.com - 
P45,2025-11-21T14:24:47Z,2025-11-21T14:43:35Z,EXPERIMENTAL,lcao1@laurentian.ca
P46,2025-11-21T14:39:58Z,2025-11-21T15:02:58Z,CONTROL,zli17@laurentian.ca
P47,NA,2025-11-19T15:09:40Z,CONTROL,ywang54@laurentian.ca - WRONG
P48,NA,2025-11-21T15:27:04Z,EXPERIMENTAL,fliu5@laurentian.ca - 

DAY OF NOTES:
- Gemini model isdsue with accents
- research solutions--pretrained w/better non-native english detection/decoding
- how often does model react/utilize the emotion info from the s
  modell
- evaluate the quality of translations of native vs non-native english speakers
- how often did model ignore/not react to emotional states of Human 
  - robot/AI would get "lost" sometimes and think that it was the researcher
  - langgraph may have been better or a RAG system depending on volume of 'known-data'
    - a fine-tuned rag may have been better to train on its role / also dividing out the two roles (culd be leakage)
- realized that inn 

  - another study could look at how cultural differences influence perception of responsiveness in robots human trust 

# Potential Journals

THRI  
1. CM Transactions on Human-Robot Interaction
2. IEEE Transactions on Robotics (T-RO)
3. International Journal of Social Robotics
4. Nature: Machine Intelligence
